export const portfolioItems = [
  {
    id: "1",
    title: "AI-Powered Analytics Dashboard",
    description: "Real-time data visualization platform with predictive insights",
    image: "/portfolio/dashboard-1.jpg",
    tags: ["Web App", "AI", "Next.js"],
    results: {
      conversion: "+40%",
      performance: "98",
      loadTime: "0.8s",
    },
    tech: ["Next.js", "TypeScript", "Tailwind", "Vercel"],
    link: "https://example.com",
    category: "web-app",
  },
  {
    id: "2",
    title: "E-commerce Platform",
    description: "Conversion-optimized storefront with AI recommendations",
    image: "/portfolio/ecommerce-1.jpg",
    tags: ["Website", "E-commerce"],
    results: {
      conversion: "+65%",
      performance: "95",
      loadTime: "0.5s",
    },
    tech: ["Next.js", "Stripe", "PostgreSQL"],
    link: "https://example.com",
    category: "website",
  },
  {
    id: "3",
    title: "Automated Workflow System",
    description: "No-code automation platform for enterprise operations",
    image: "/portfolio/automation-1.jpg",
    tags: ["AI Automation", "Enterprise"],
    results: {
      conversion: "80% time saved",
      performance: "99.9% uptime",
      loadTime: "N/A",
    },
    tech: ["n8n", "Node.js", "PostgreSQL"],
    link: "https://example.com",
    category: "automation",
  },
  {
    id: "4",
    title: "Customer Support Agent",
    description: "Intelligent chatbot handling 90% of support queries",
    image: "/portfolio/agent-1.jpg",
    tags: ["AI Agent", "Chatbot"],
    results: {
      conversion: "90% resolved",
      performance: "95% accuracy",
      loadTime: "<100ms",
    },
    tech: ["OpenAI", "Python", "FastAPI"],
    link: "https://example.com",
    category: "agent",
  },
  {
    id: "5",
    title: "AI Infrastructure Platform",
    description: "Scalable MLOps pipeline for production AI models",
    image: "/portfolio/infrastructure-1.jpg",
    tags: ["AI Infrastructure", "MLOps"],
    results: {
      conversion: "99.9% uptime",
      performance: "10x throughput",
      loadTime: "N/A",
    },
    tech: ["Kubernetes", "TensorFlow", "Python"],
    link: "https://example.com",
    category: "infrastructure",
  },
  {
    id: "6",
    title: "SaaS Landing Page",
    description: "Conversion-focused landing page with A/B testing",
    image: "/portfolio/landing-1.jpg",
    tags: ["Website", "Marketing"],
    results: {
      conversion: "+120%",
      performance: "97",
      loadTime: "0.3s",
    },
    tech: ["Next.js", "Tailwind", "Vercel Edge"],
    link: "https://example.com",
    category: "website",
  },
];

export const portfolioCategories = [
  "All",
  "Website",
  "Web App",
  "AI Automation",
  "AI Agent",
  "AI Infrastructure",
];

